name: "Terraform Apply Staging"
 
on:
  pull_request:
    branches:
      - main
    paths:
      - src/Infraestructure/Provisioning/modules/api/**
  workflow_dispatch:

jobs:
  terraform:
    uses: manuel-rodriguez/terraform-template/.github/workflows/terraform-workflow.yml@main
    with:
      cloud_organization: "Mers"
      tf_workspace: "terraform-production"
      config_directory: "src/Infraestructure/Provisioning/modules/api/"
    secrets:
      tf_api_token: ${{ secrets.TF_API_TOKEN }} 